allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js-pure: true
  prisma: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
  vscode-ripgrep: true
  vue-demi: set this to true or false
minimumReleaseAgeExclude:
  - '@scalar/agent-chat@0.12.30'
  - '@scalar/api-client@3.18.0'
  - '@scalar/api-reference-react@0.9.67'
  - '@scalar/api-reference@1.68.0'
  - '@scalar/asyncapi-upgrader@0.1.9'
  - '@scalar/blocks@0.1.16'
  - '@scalar/components@0.29.1'
  - '@scalar/helpers@0.11.3'
  - '@scalar/json-magic@0.13.4'
  - '@scalar/oas-utils@0.19.16'
  - '@scalar/schemas@0.9.0'
  - '@scalar/sidebar@0.11.1'
  - '@scalar/snippetz@0.9.30'
  - '@scalar/types@0.19.0'
  - '@scalar/use-hooks@0.4.11'
  - '@scalar/workspace-store@0.60.0'
  - '@oxfmt/binding-android-arm-eabi@0.67.0'
  - '@oxfmt/binding-android-arm64@0.67.0'
  - '@oxfmt/binding-darwin-arm64@0.67.0'
  - '@oxfmt/binding-darwin-x64@0.67.0'
  - '@oxfmt/binding-freebsd-x64@0.67.0'
  - '@oxfmt/binding-linux-arm-gnueabihf@0.67.0'
  - '@oxfmt/binding-linux-arm-musleabihf@0.67.0'
  - '@oxfmt/binding-linux-arm64-gnu@0.67.0'
  - '@oxfmt/binding-linux-arm64-musl@0.67.0'
  - '@oxfmt/binding-linux-ppc64-gnu@0.67.0'
  - '@oxfmt/binding-linux-riscv64-gnu@0.67.0'
  - '@oxfmt/binding-linux-riscv64-musl@0.67.0'
  - '@oxfmt/binding-linux-s390x-gnu@0.67.0'
  - '@oxfmt/binding-linux-x64-gnu@0.67.0'
  - '@oxfmt/binding-linux-x64-musl@0.67.0'
  - '@oxfmt/binding-openharmony-arm64@0.67.0'
  - '@oxfmt/binding-win32-arm64-msvc@0.67.0'
  - '@oxfmt/binding-win32-ia32-msvc@0.67.0'
  - '@oxfmt/binding-win32-x64-msvc@0.67.0'
  - '@oxlint/binding-android-arm-eabi@1.82.0'
  - '@oxlint/binding-android-arm64@1.82.0'
  - '@oxlint/binding-darwin-arm64@1.82.0'
  - '@oxlint/binding-darwin-x64@1.82.0'
  - '@oxlint/binding-freebsd-x64@1.82.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.82.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.82.0'
  - '@oxlint/binding-linux-arm64-gnu@1.82.0'
  - '@oxlint/binding-linux-arm64-musl@1.82.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.82.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.82.0'
  - '@oxlint/binding-linux-riscv64-musl@1.82.0'
  - '@oxlint/binding-linux-s390x-gnu@1.82.0'
  - '@oxlint/binding-linux-x64-gnu@1.82.0'
  - '@oxlint/binding-linux-x64-musl@1.82.0'
  - '@oxlint/binding-openharmony-arm64@1.82.0'
  - '@oxlint/binding-win32-arm64-msvc@1.82.0'
  - '@oxlint/binding-win32-ia32-msvc@1.82.0'
  - '@oxlint/binding-win32-x64-msvc@1.82.0'
  - oxfmt@0.67.0
  - oxlint@1.82.0
